-- TMS 运费对账表
CREATE TABLE IF NOT EXISTS `tms_freight_reconciliation` (
    `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no`              VARCHAR(64)  NOT NULL COMMENT '对账单号',
    `carrier_id`      BIGINT       NOT NULL COMMENT '承运商编号',
    `period_start`    DATE         NOT NULL COMMENT '对账周期开始日期',
    `period_end`      DATE         NOT NULL COMMENT '对账周期结束日期',
    `system_amount`   DECIMAL(18,2) DEFAULT 0 COMMENT '系统运费总额',
    `carrier_amount`  DECIMAL(18,2) DEFAULT 0 COMMENT '承运商账单金额',
    `diff_amount`     DECIMAL(18,2) DEFAULT 0 COMMENT '差异金额',
    `status`          INT          NOT NULL DEFAULT 0 COMMENT '对账状态（0待对账/10已对账/20有差异/30已确认/40已驳回）',
    `reconciler_id`   BIGINT       DEFAULT NULL COMMENT '对账人',
    `reconcile_time`  DATETIME     DEFAULT NULL COMMENT '对账时间',
    `confirmer_id`    BIGINT       DEFAULT NULL COMMENT '确认人',
    `confirm_time`    DATETIME     DEFAULT NULL COMMENT '确认时间',
    `remark`          VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `creator`         VARCHAR(64)  DEFAULT '' COMMENT '创建者',
    `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`         VARCHAR(64)  DEFAULT '' COMMENT '更新者',
    `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`         BIT(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id`       BIGINT       NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_no` (`no`, `tenant_id`),
    KEY `idx_carrier_id` (`carrier_id`),
    KEY `idx_status` (`status`),
    KEY `idx_period` (`period_start`, `period_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TMS 运费对账表';

-- TMS 车队运营表
CREATE TABLE IF NOT EXISTS `tms_fleet_operation` (
    `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `vehicle_id`         BIGINT       NOT NULL COMMENT '车辆编号',
    `operation_date`     DATE         NOT NULL COMMENT '运营日期',
    `mileage`            DECIMAL(10,2) DEFAULT 0 COMMENT '行驶里程（公里）',
    `fuel_consumption`   DECIMAL(10,2) DEFAULT 0 COMMENT '油耗（升）',
    `fuel_cost`          DECIMAL(18,2) DEFAULT 0 COMMENT '油费（元）',
    `maintenance_cost`   DECIMAL(18,2) DEFAULT 0 COMMENT '维修保养费（元）',
    `insurance_cost`     DECIMAL(18,2) DEFAULT 0 COMMENT '保险费（元）',
    `inspection_cost`    DECIMAL(18,2) DEFAULT 0 COMMENT '年检费（元）',
    `revenue`            DECIMAL(18,2) DEFAULT 0 COMMENT '运营收入（元）',
    `total_cost`         DECIMAL(18,2) DEFAULT 0 COMMENT '总运营成本（元）',
    `profit`             DECIMAL(18,2) DEFAULT 0 COMMENT '运营利润（元）',
    `remark`             VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `creator`            VARCHAR(64)  DEFAULT '' COMMENT '创建者',
    `create_time`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`            VARCHAR(64)  DEFAULT '' COMMENT '更新者',
    `update_time`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`            BIT(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id`          BIGINT       NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_vehicle_id` (`vehicle_id`),
    KEY `idx_operation_date` (`operation_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TMS 车队运营表';
