-- ============================================================================
-- ERP 模块 H2 测试 schema（最小种子）
-- ----------------------------------------------------------------------------
-- 说明：本文件为 P1-1 日终对账「只读投影适配」阶段的最小 schema 种子，仅包含
--   - erp_stock           ：ERP 产品库存表（投影侧）
--   - inventory_item      ：P1-4 共享库存真值源（对账真值侧）
-- 用于验证 ErpInventoryProjectionReader 与共享 Starter 日终对账的端到端链路。
--
-- 注意：ERP 全量业务表 schema 在 Task #94（M2 阶段 A 写路径改写）随 DB 测试基座一并建立，
--       本种子文件不应被视为 ERP 完整 schema。
-- ============================================================================

-- ----------------------------
-- ERP 产品库存（投影侧）
-- ----------------------------
CREATE TABLE IF NOT EXISTS "erp_stock" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "version" bigint NOT NULL DEFAULT 0,
    "product_id" bigint DEFAULT NULL,
    "warehouse_id" bigint DEFAULT NULL,
    "count" decimal(20, 2) NOT NULL DEFAULT 0,
    "locked_count" decimal(20, 2) NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- P1-4 共享库存条目（单一真值源承载表，M2 日终对账真值侧）
-- 与 yudao-server/src/main/resources/db/migration/V81__inventory_item.sql 对齐（H2 MySQL 模式镜像）
-- ----------------------------
CREATE TABLE IF NOT EXISTS "inventory_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "version" bigint NOT NULL DEFAULT 0,
    "item_id" bigint NOT NULL,
    "warehouse_id" bigint NOT NULL,
    "location_id" bigint NOT NULL DEFAULT 0,
    "area_id" bigint NOT NULL DEFAULT 0,
    "batch_id" bigint NOT NULL DEFAULT 0,
    "batch_code" varchar(64) DEFAULT NULL,
    "quantity" decimal(20, 2) NOT NULL DEFAULT 0,
    "locked_count" decimal(20, 2) NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    UNIQUE KEY "uk_item_warehouse_location_area_batch" ("item_id", "warehouse_id", "location_id", "area_id", "batch_id")
);
