CREATE TABLE IF NOT EXISTS "crm_business" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "customer_id" bigint,
    "follow_up_status" bit,
    "contact_last_time" timestamp,
    "contact_next_time" timestamp,
    "owner_user_id" bigint,
    "status_type_id" bigint,
    "status_id" bigint,
    "end_status" int,
    "end_remark" varchar(255),
    "deal_time" timestamp,
    "total_product_price" decimal(20,2),
    "discount_percent" decimal(20,2),
    "total_price" decimal(20,2),
    "remark" varchar(255),
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_business_product" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "business_id" bigint,
    "product_id" bigint,
    "product_price" decimal(20,2),
    "business_price" decimal(20,2),
    "count" decimal(20,2),
    "total_price" decimal(20,2),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_business_status" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type_id" bigint,
    "name" varchar(255),
    "percent" int,
    "sort" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_business_status_type" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "dept_ids" varchar(1024),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_clue" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "follow_up_status" bit,
    "contact_last_time" timestamp,
    "contact_last_content" varchar(255),
    "contact_next_time" timestamp,
    "owner_user_id" bigint,
    "receive_count" int,
    "transform_status" bit,
    "customer_id" bigint,
    "mobile" varchar(255),
    "telephone" varchar(255),
    "qq" varchar(255),
    "wechat" varchar(255),
    "email" varchar(255),
    "area_id" int,
    "detail_address" varchar(255),
    "industry_id" int,
    "level" int,
    "source" int,
    "remark" varchar(255),
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_clue_channel" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "channel_name" varchar(255),
    "channel_type" int,
    "channel_code" varchar(255),
    "api_url" varchar(255),
    "api_key" varchar(255),
    "auto_assign_user_id" bigint,
    "status" int,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_clue_pool_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "enabled" bit,
    "contact_expire_days" int,
    "notify_enabled" bit,
    "notify_days" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contact" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "customer_id" bigint,
    "contact_last_time" timestamp,
    "contact_last_content" varchar(255),
    "contact_next_time" timestamp,
    "owner_user_id" bigint,
    "mobile" varchar(255),
    "telephone" varchar(255),
    "email" varchar(255),
    "qq" bigint,
    "wechat" varchar(255),
    "area_id" int,
    "detail_address" varchar(255),
    "sex" int,
    "master" bit,
    "post" varchar(255),
    "parent_id" bigint,
    "remark" varchar(255),
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contact_business" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contact_id" bigint,
    "business_id" bigint,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contract" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "no" varchar(255),
    "customer_id" bigint,
    "business_id" bigint,
    "contact_last_time" timestamp,
    "owner_user_id" bigint,
    "process_instance_id" varchar(255),
    "audit_status" int,
    "order_date" timestamp,
    "start_time" timestamp,
    "end_time" timestamp,
    "total_product_price" decimal(20,2),
    "discount_percent" decimal(20,2),
    "total_price" decimal(20,2),
    "sign_contact_id" bigint,
    "sign_user_id" bigint,
    "remark" varchar(255),
    "file_urls" varchar(1024),
    "esign_task_id" varchar(255),
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contract_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "notify_enabled" bit,
    "notify_days" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_contract_product" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_id" bigint,
    "product_id" bigint,
    "product_price" decimal(20,2),
    "contract_price" decimal(20,2),
    "count" decimal(20,2),
    "total_price" decimal(20,2),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_customer" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "follow_up_status" bit,
    "contact_last_time" timestamp,
    "contact_last_content" varchar(255),
    "contact_next_time" timestamp,
    "owner_user_id" bigint,
    "owner_time" timestamp,
    "lock_status" bit,
    "deal_status" bit,
    "mobile" varchar(255),
    "telephone" varchar(255),
    "qq" varchar(255),
    "wechat" varchar(255),
    "email" varchar(255),
    "area_id" int,
    "detail_address" varchar(255),
    "industry_id" int,
    "level" int,
    "source" int,
    "remark" varchar(255),
    "tag_ids" varchar(1024),
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_customer_limit_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" int,
    "user_ids" varchar(1024),
    "dept_ids" varchar(1024),
    "max_count" int,
    "deal_count_enabled" bit,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_customer_pool_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "enabled" bit,
    "contact_expire_days" int,
    "deal_expire_days" int,
    "notify_enabled" bit,
    "notify_days" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_follow_up_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "biz_type" int,
    "biz_id" bigint,
    "type" int,
    "content" varchar(255),
    "next_time" timestamp,
    "pic_urls" varchar(1024),
    "file_urls" varchar(1024),
    "business_ids" varchar(1024),
    "contact_ids" varchar(1024),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_invoice" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(255),
    "contract_id" bigint,
    "customer_id" bigint,
    "contact_id" bigint,
    "invoice_type" int,
    "invoice_no" varchar(255),
    "buyer_name" varchar(255),
    "buyer_tax_no" varchar(255),
    "amount_without_tax" decimal(20,2),
    "tax_amount" decimal(20,2),
    "amount_with_tax" decimal(20,2),
    "invoice_date" date,
    "audit_status" int,
    "process_instance_id" varchar(255),
    "owner_user_id" bigint,
    "file_urls" varchar(1024),
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_invoice_line" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "invoice_id" bigint,
    "product_name" varchar(255),
    "quantity" decimal(20,2),
    "unit_price" decimal(20,2),
    "amount_without_tax" decimal(20,2),
    "tax_rate" decimal(20,2),
    "tax_amount" decimal(20,2),
    "amount_with_tax" decimal(20,2),
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_owner_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "biz_type" int,
    "biz_id" bigint,
    "pre_owner_user_id" bigint,
    "post_owner_user_id" bigint,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_performance_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "biz_type" int,
    "object_id" bigint,
    "object_type" int,
    "year" int,
    "year_target_price" decimal(20,2),
    "january_target_price" decimal(20,2),
    "february_target_price" decimal(20,2),
    "march_target_price" decimal(20,2),
    "april_target_price" decimal(20,2),
    "may_target_price" decimal(20,2),
    "june_target_price" decimal(20,2),
    "july_target_price" decimal(20,2),
    "august_target_price" decimal(20,2),
    "september_target_price" decimal(20,2),
    "october_target_price" decimal(20,2),
    "november_target_price" decimal(20,2),
    "december_target_price" decimal(20,2),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_permission" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "biz_type" int,
    "biz_id" bigint,
    "user_id" bigint,
    "level" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_product" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "no" varchar(255),
    "unit" int,
    "price" decimal(20,2),
    "status" int,
    "category_id" bigint,
    "description" varchar(255),
    "owner_user_id" bigint,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_product_category" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "parent_id" bigint,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_receivable" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(255),
    "plan_id" bigint,
    "customer_id" bigint,
    "contract_id" bigint,
    "owner_user_id" bigint,
    "return_time" timestamp,
    "return_type" int,
    "price" decimal(20,2),
    "remark" varchar(255),
    "process_instance_id" varchar(255),
    "audit_status" int,
    "version" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    UNIQUE KEY "uk_contract_no" ("contract_id", "no")
);

CREATE TABLE IF NOT EXISTS "crm_receivable_plan" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "period" int,
    "customer_id" bigint,
    "contract_id" bigint,
    "owner_user_id" bigint,
    "return_time" timestamp,
    "return_type" int,
    "price" decimal(20,2),
    "receivable_id" bigint,
    "remind_days" int,
    "remind_time" timestamp,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_sale_order" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(255),
    "contract_id" bigint,
    "customer_id" bigint,
    "business_id" bigint,
    "contact_id" bigint,
    "order_date" timestamp,
    "delivery_date" timestamp,
    "total_amount" decimal(20,2),
    "discount_amount" decimal(20,2),
    "payment_status" int,
    "delivery_status" int,
    "status" int,
    "owner_user_id" bigint,
    "process_instance_id" varchar(255),
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_sale_order_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_id" bigint,
    "product_id" bigint,
    "product_name" varchar(255),
    "quantity" decimal(20,2),
    "unit_price" decimal(20,2),
    "discount" decimal(20,2),
    "amount" decimal(20,2),
    "tax_rate" decimal(20,2),
    "tax_amount" decimal(20,2),
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_visit_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" bigint,
    "contact_id" bigint,
    "owner_user_id" bigint,
    "visit_time" timestamp,
    "sign_in_time" timestamp,
    "sign_in_latitude" decimal(20,2),
    "sign_in_longitude" decimal(20,2),
    "sign_in_address" varchar(255),
    "visit_type" int,
    "content" varchar(255),
    "pic_urls" varchar(1024),
    "file_urls" varchar(1024),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "crm_work_order" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(255),
    "title" varchar(255),
    "customer_id" bigint,
    "contact_id" bigint,
    "product_id" bigint,
    "work_order_type" int,
    "priority" int,
    "description" varchar(255),
    "status" int,
    "assignee_user_id" bigint,
    "resolution" varchar(255),
    "respond_time" timestamp,
    "resolve_time" timestamp,
    "sla_deadline" timestamp,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);
