-- ----------------------------
-- QMS 检验项目表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "qms_inspection_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(255) NOT NULL,
    "type" int NOT NULL,
    "method" int NOT NULL,
    "standard" varchar(500) DEFAULT NULL,
    "target" varchar(100) DEFAULT NULL,
    "upper_limit" decimal(20,4) DEFAULT NULL,
    "lower_limit" decimal(20,4) DEFAULT NULL,
    "unit" varchar(32) DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "status" int DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- QMS 检验单表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "qms_inspection_order" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_no" varchar(64) NOT NULL,
    "type" int NOT NULL,
    "supplier_id" bigint DEFAULT NULL,
    "batch_no" varchar(64) DEFAULT NULL,
    "work_order_id" bigint DEFAULT NULL,
    "product_id" bigint DEFAULT NULL,
    "inspector" varchar(64) DEFAULT NULL,
    "inspect_time" timestamp DEFAULT NULL,
    "status" int DEFAULT 10,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- QMS 检验记录表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "qms_inspection_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_id" bigint NOT NULL,
    "item_id" bigint NOT NULL,
    "measured_value" varchar(100) DEFAULT NULL,
    "result" int DEFAULT NULL,
    "inspector" varchar(64) DEFAULT NULL,
    "inspect_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- QMS CAPA 纠正预防措施文档表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "qms_capa_document" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "capa_no" varchar(64) NOT NULL,
    "source" int NOT NULL,
    "priority" int DEFAULT NULL,
    "stage" int DEFAULT 10,
    "problem" clob DEFAULT NULL,
    "cause" clob DEFAULT NULL,
    "root_cause_analysis" clob DEFAULT NULL,
    "corrective_action" clob DEFAULT NULL,
    "preventive_action" clob DEFAULT NULL,
    "responsible_person" varchar(64) DEFAULT NULL,
    "due_date" timestamp DEFAULT NULL,
    "close_date" timestamp DEFAULT NULL,
    "status" int DEFAULT 10,
    "verification_result" int DEFAULT NULL,
    "verification_comment" clob DEFAULT NULL,
    "verified_by" varchar(64) DEFAULT NULL,
    "verified_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- QMS 8D 报告表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "qms_eight_d_report" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "report_no" varchar(64) NOT NULL,
    "title" varchar(255) DEFAULT NULL,
    "ncr_id" bigint DEFAULT NULL,
    "capa_id" bigint DEFAULT NULL,
    "status" int DEFAULT 0,
    "d1_team_members" clob DEFAULT NULL,
    "d2_problem_description" clob DEFAULT NULL,
    "d3_interim_action" clob DEFAULT NULL,
    "d4_root_cause" clob DEFAULT NULL,
    "d5_permanent_action" clob DEFAULT NULL,
    "d6_implementation_result" clob DEFAULT NULL,
    "d7_prevention_action" clob DEFAULT NULL,
    "d8_team_recognition" clob DEFAULT NULL,
    "close_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
