#!/usr/bin/env python3
# Generate H2 create_tables.sql for yudao-module-crm unit tests from DO classes.
import os, re, glob

BASE = r"D:/Desktop/yudao/yudao-module-crm/src/main/java"
OUT = r"D:/Desktop/yudao/yudao-module-crm/src/test/resources/sql/create_tables.sql"

TYPE_MAP = {
    "Long": "bigint", "long": "bigint",
    "Integer": "int", "int": "int",
    "Short": "smallint", "short": "smallint",
    "Byte": "tinyint", "byte": "tinyint",
    "Boolean": "bit", "boolean": "bit",
    "String": "varchar(255)",
    "BigDecimal": "decimal(20,2)",
    "Double": "double precision", "double": "double precision",
    "Float": "float", "float": "float",
    "LocalDateTime": "timestamp",
    "LocalDate": "date",
    "byte[]": "blob",
}

def snake(name):
    s = re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()
    return s

def java_type(t):
    # strip generics
    t = t.split("<")[0].strip()
    return TYPE_MAP.get(t, "varchar(255)")

def parse_file(path):
    with open(path, encoding="utf-8") as f:
        src = f.read()

    m = re.search(r'@TableName\s*\(\s*(?:value\s*=\s*)?"([^"]+)"', src)
    if not m:
        return None
    table = m.group(1)

    base = "TenantBaseDO" if re.search(r'extends\s+TenantBaseDO', src) else "BaseDO"

    # collect fields
    fields = []
    # find field declarations with optional preceding annotation lines
    # We'll scan line by line
    lines = src.splitlines()
    pending = []  # annotation lines
    for line in lines:
        st = line.strip()
        if st.startswith("@"):
            pending.append(st)
            continue
        fm = re.match(r'(?:private|protected)\s+([\w\.<>\[\],\s]+?)\s+(\w+)\s*;', st)
        if not fm:
            # not a field; reset pending unless it's part of multiline annotation (handled above)
            pending = []
            continue
        ann = " ".join(pending)
        pending = []
        ftype = fm.group(1).strip()
        fname = fm.group(2)
        # skip non-persistent
        if "exist = false" in ann:
            continue
        # collection / map fields are persisted via a TypeHandler as a string column
        if "<" in ftype and "byte[]" not in ftype:
            h2 = "varchar(1024)"
        else:
            h2 = java_type(ftype)
        # skip static / final
        if "static" in st or "final" in st:
            continue
        # column name
        col = fname
        vm = re.search(r'value\s*=\s*"([^"]+)"', ann)
        if vm:
            col = vm.group(1)
        else:
            col = snake(fname)
        is_pk = "@TableId" in ann
        fields.append((col, h2, is_pk))
    return table, base, fields

def emit(table, base, fields):
    cols = []
    pk = None
    for col, h2, is_pk in fields:
        if is_pk:
            pk = col
            cols.append(f'    "{col}" {h2} NOT NULL GENERATED BY DEFAULT AS IDENTITY')
        else:
            cols.append(f'    "{col}" {h2}')
    # audit columns from BaseDO
    cols.append('    "creator" varchar(64) DEFAULT \'\'')
    cols.append('    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP')
    cols.append('    "updater" varchar(64) DEFAULT \'\'')
    cols.append('    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP')
    cols.append('    "deleted" bit NOT NULL DEFAULT FALSE')
    if base == "TenantBaseDO":
        cols.append('    "tenant_id" bigint NOT NULL DEFAULT \'0\'')
    pkcol = pk or "id"
    cols.append(f'    PRIMARY KEY ("{pkcol}")')
    body = ",\n".join(cols)
    return f'CREATE TABLE IF NOT EXISTS "{table}" (\n{body}\n);\n'

results = []
seen = set()
for path in glob.glob(os.path.join(BASE, "**", "*.java"), recursive=True):
    r = parse_file(path)
    if r and r[0] not in seen:
        seen.add(r[0])
        results.append(r)

results.sort(key=lambda x: x[0])
out_parts = []
for table, base, fields in results:
    out_parts.append(emit(table, base, fields))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out_parts))
print(f"Generated {len(results)} tables -> {OUT}")
for t, b, flds in results:
    print(f"  {t} ({b}) cols={len(flds)}")
