#!/usr/bin/env python3
# 通用工具：为某个 yudao 业务模块生成单元测试用的 H2 DDL。
# 扫描 <module>/src/main/java 下所有带 @TableName 的 DO 类，
# 生成：
#   <module>/src/test/resources/sql/create_tables.sql  (H2 建表)
#   <module>/src/test/resources/sql/clean.sql          (@Sql 每个方法后清库)
# 列名 snake_case；id 用 GENERATED BY DEFAULT AS IDENTITY；
# 补 BaseDO 审计列；TenantBaseDO 补 tenant_id；
# List/Map 字段经 TypeHandler 存 varchar(1024)。
import os, re, glob, sys, argparse

REPO = r"D:/Desktop/yudao"
TYPE_MAP = {
    "Long": "bigint", "long": "bigint",
    "Integer": "int", "int": "int",
    "Short": "smallint", "short": "smallint",
    "Byte": "tinyint", "byte": "tinyint",
    "Boolean": "bit", "boolean": "bit",
    "String": "varchar(255)",
    "BigDecimal": "decimal(20,2)",
    "Double": "double precision", "double": "double precision",
    "Float": "float", "float": "float",
    "LocalDateTime": "timestamp",
    "LocalDate": "date",
    "byte[]": "blob",
}

def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

def java_type(t):
    t = t.split("<")[0].strip()
    return TYPE_MAP.get(t, "varchar(255)")

def parse_file(path):
    with open(path, encoding="utf-8") as f:
        src = f.read()
    m = re.search(r'@TableName\s*\(\s*(?:value\s*=\s*)?"([^"]+)"', src)
    if not m:
        return None
    table = m.group(1)
    base = "TenantBaseDO" if re.search(r'extends\s+TenantBaseDO', src) else "BaseDO"
    fields = []
    lines = src.splitlines()
    pending = []
    for line in lines:
        st = line.strip()
        if st.startswith("@"):
            pending.append(st)
            continue
        fm = re.match(r'(?:private|protected|public)?\s*([\w\.<>\[\],\s]+?)\s+(\w+)\s*;', st)
        if not fm:
            pending = []
            continue
        if "(" in st:  # 跳过方法调用/声明，避免把方法体局部变量误判为字段
            pending = []
            continue
        ann = " ".join(pending)
        pending = []
        ftype = fm.group(1).strip()
        fname = fm.group(2)
        if "exist = false" in ann:
            continue
        if "static" in st or "final" in st:
            continue
        if "<" in ftype and "byte[]" not in ftype:
            h2 = "varchar(1024)"
        else:
            h2 = java_type(ftype)
        col = fname
        vm = re.search(r'value\s*=\s*"([^"]+)"', ann)
        col = vm.group(1) if vm else snake(fname)
        is_pk = "@TableId" in ann
        fields.append((col, h2, is_pk))
    return table, base, fields

def emit(table, base, fields):
    cols = []
    pk = None
    for col, h2, is_pk in fields:
        if is_pk:
            pk = col
            cols.append(f'    "{col}" {h2} NOT NULL GENERATED BY DEFAULT AS IDENTITY')
        else:
            cols.append(f'    "{col}" {h2}')
    cols.append('    "creator" varchar(64) DEFAULT \'\'')
    cols.append('    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP')
    cols.append('    "updater" varchar(64) DEFAULT \'\'')
    cols.append('    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP')
    cols.append('    "deleted" bit NOT NULL DEFAULT FALSE')
    if base == "TenantBaseDO":
        cols.append('    "tenant_id" bigint NOT NULL DEFAULT \'0\'')
    pkcol = pk or "id"
    cols.append(f'    PRIMARY KEY ("{pkcol}")')
    body = ",\n".join(cols)
    return f'CREATE TABLE IF NOT EXISTS "{table}" (\n{body}\n);\n'

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("module", help="模块目录名，如 yudao-module-tms")
    args = ap.parse_args()
    module = args.module
    base_dir = os.path.join(REPO, module, "src", "main", "java")
    out_dir = os.path.join(REPO, module, "src", "test", "resources", "sql")
    if not os.path.isdir(base_dir):
        print(f"ERROR: 找不到 {base_dir}")
        sys.exit(1)
    results = []
    seen = set()
    for path in glob.glob(os.path.join(base_dir, "**", "*.java"), recursive=True):
        r = parse_file(path)
        if r and r[0] not in seen:
            seen.add(r[0])
            results.append(r)
    results.sort(key=lambda x: x[0])
    os.makedirs(out_dir, exist_ok=True)
    create_sql = "\n".join(emit(t, b, f) for t, b, f in results)
    with open(os.path.join(out_dir, "create_tables.sql"), "w", encoding="utf-8") as f:
        f.write(create_sql)
    tables = [t for t, _, _ in results]
    clean_lines = ["-- 每个单元测试结束后，清理 DB（与 create_tables.sql 的表保持一致）\n"]
    clean_lines += [f'DELETE FROM "{t}";' for t in tables]
    with open(os.path.join(out_dir, "clean.sql"), "w", encoding="utf-8") as f:
        f.write("\n".join(clean_lines) + "\n")
    print(f"Generated {len(results)} tables -> {out_dir}")
    for t, b, flds in results:
        print(f"  {t} ({b}) cols={len(flds)}")

if __name__ == "__main__":
    main()
