<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.zhicloud</groupId>
        <artifactId>zhicloud</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <artifactId>zhicloud-module-hr</artifactId>

    <name>${project.artifactId}</name>
    <description>
        hr 模块下，人力资源管理（Human Resources）。
        覆盖员工档案、部门、职位、考勤、薪资、绩效等企业级人力资源管控能力
    </description>

    <dependencies>
        <!-- 业务组件 -->
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-biz-tenant</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-excel</artifactId>
        </dependency>

        <!-- Spring Modulith 模块声明（package-info.java 使用 @ApplicationModule） -->
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-core</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>cn.zhicloud</groupId>
            <artifactId>zhicloud-spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
